[window]
decorations = "none"
opacity = 0.8
startup_mode = "Maximized"


[window.padding]
x = 10
y = 10


[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"


[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"


[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"


[env]
TERM = "alacritty"


[font]
size = 20.0


[font.bold]
family = "PlemolJP Console NF"
style = "Bold"


[font.bold_italic]
family = "PlemolJP Console NF"
style = "Bold Italic"


[font.italic]
family = "PlemolJP Console NF"
style = "Italic"


[font.normal]
family = "PlemolJP Console NF"
style = "Regular"
