env:
  TERM: alacritty

window:
  padding:
    x: 10
    y: 10
  decorations: none
  opacity: 0.8
  startup_mode: Maximized

font:
  size: 20.0

  normal:
    family: PlemolJP Console NF
    style: Regular

  bold:
    family: PlemolJP Console NF
    style: Bold

  italic:
    family: PlemolJP Console NF
    style: Italic

  bold_italic:
    family: PlemolJP Console NF
    style: Bold Italic

colors:
  name: TokyoNight Night
  author: Folke

  # Default colors
  primary:
    background: "0x1a1b26"
    foreground: "0xc0caf5"

  # Normal colors
  normal:
    black: "0x15161E"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xa9b1d6"

  # Bright colors
  bright:
    black: "0x414868"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xc0caf5"

  indexed_colors:
    - { index: 16, color: "0xff9e64" }
    - { index: 17, color: "0xdb4b4b" }
theme: Tokyonight_Night

hints:
  start:
    foreground: "#1d1f21"
    background: "#e9ff5e"
  end:
    foreground: "#e9ff5e"
    background: "#1d1f21"
  footer_bar:
    background: "#c5c8c6"
    foreground: "#1d1f21"

key_bindings:
  - { key: Tab, mods: Control, chars: "[27;5;9~" }
  - { key: Tab, mods: Shift, chars: "[27;2;9~" }
  - { key: Tab, mods: Control|Shift, chars: "[27;6;9~" }
