tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "readline"
brew "sqlite"
brew "xz"
brew "python@3.9"
brew "ffmpeg"
brew "mas"
brew "nkf"
brew "pwgen"
brew "screen"
brew "starship"
brew "tree"
brew "volta"
brew "youtube-dl"
cask "adguard"
cask "appcleaner"
cask "autodesk-fusion360"
cask "blender"
cask "cmd-eikana"
cask "deepl"
cask "discord"
cask "docker"
cask "figma"
cask "google-chrome"
cask "grammarly"
cask "imageoptim"
cask "kindle"
cask "shiftit"
cask "slack"
cask "visual-studio-code"
cask "vrew"
cask "zoom"
mas "Final Cut Pro", id: 424389933
mas "Just Focus", id: 1142151959
mas "Keepa - Price Tracker", id: 1533805339
mas "uBlacklist for Safari", id: 1547912640
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
