# Managed by scripts/brewfile-manager.sh.
# Formulae, taps, and cross-platform casks are shared by default. Darwin-only apps and overrides live in .Brewfile.darwin.

# Shared packages
tap "entireio/tap"
tap "schroneko/tap"
tap "xdevplatform/tap"
brew "autoconf"
brew "autoconf-archive"
brew "automake"
brew "ccache"
brew "cloudflared", restart_service: :changed
brew "cmake"
brew "coreutils"
brew "fastmcp"
brew "ffmpeg"
brew "flyctl"
brew "fzf"
brew "gcc"
brew "gh"
brew "ghq"
brew "git"
brew "git-lfs"
brew "glow"
brew "hf"
brew "imagemagick"
brew "jq"
brew "libass"
brew "marp-cli"
brew "mise"
brew "mupdf-tools"
brew "nasm"
brew "ncdu"
brew "neovim"
brew "ninja"
brew "nmap"
brew "oci-cli"
brew "openjdk"
brew "pdfcpu"
brew "pkgconf"
brew "poppler"
brew "portaudio"
brew "presenterm"
brew "qpdf"
brew "ripgrep"
brew "schroneko/tap/castkit"
brew "stow"
brew "syncthing", restart_service: :changed
brew "tesseract-lang"
brew "timg"
brew "tmux"
brew "tree"
brew "uv"
brew "yt-dlp"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "1password-cli"
cask "claude-code"
cask "codex"

# Darwin-only packages
brew "container"
brew "mint"
brew "xcodegen"
cask "1password"
cask "antigravity"
cask "arc"
cask "capcut"
cask "chatgpt"
cask "claude"
cask "cleanshot"
cask "codex-app"
cask "comfyui"
cask "discord"
cask "font-plemol-jp-nf"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "homerow"
cask "keycastr"
cask "lm-studio"
cask "monitorcontrol"
cask "ollama-app"
cask "rectangle"
cask "screen-studio"
cask "slack"
cask "tailscale-app"
cask "zoom"

# Linux-only packages
