tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "readline"
brew "sqlite"
brew "xz"
brew "python@3.9"
brew "cocoapods"
brew "deno"
brew "ffmpeg"
brew "hdf5"
brew "lima"
brew "mas"
brew "nkf"
brew "openssl@3"
brew "pwgen"
brew "six"
brew "starship"
brew "tree"
brew "youtube-dl"
brew "zlib"
cask "adguard"
cask "appcleaner"
cask "autodesk-fusion360"
cask "blender"
cask "discord"
cask "docker"
cask "figma"
cask "google-chrome"
cask "grammarly"
cask "imageoptim"
cask "shiftit"
cask "slack"
cask "visual-studio-code"
cask "vrew"
cask "zoom"
mas "Final Cut Pro", id: 424389933
mas "Keepa - Price Tracker", id: 1533805339
mas "uBlacklist for Safari", id: 1547912640
mas "Xcode", id: 497799835
